services:
  - type: web
    name: youtube-transcript-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PYTHONHTTPSVERIFY
        value: "0"
      - key: CURL_CA_BUNDLE
        value: ""
      - key: REQUESTS_CA_BUNDLE
        value: ""
      - key: PYTHONPATH
        value: /opt/render/project/src